In [1]:
import random

In [2]:
a = random.random()
print(a)

0.6029884786888542


In [4]:
a = random.uniform(1,10)
print(a)

7.294515810803342


In [9]:
# Upper bound may be included -> Returns integer
a = random.randint(1,10)
print(a)

6


In [10]:
# Upper bound not included -> Returns integer
a = random.randrange(1,10)
print(a)

5


In [12]:
# Normal distribution
a = random.normalvariate(0,1)
print(a)

0.07538465136695216


In [13]:
mylist = list("ABCDEFGH")
a = random.choice(mylist)
print(a)

B


In [14]:
# element is not repeated
a = random.sample(mylist, 3)
print(a)

['G', 'H', 'C']


In [16]:
# sampling with repetition
a = random.choices(mylist, k = 3)
print(a)

['H', 'E', 'E']


In [18]:
random.shuffle(mylist)
print(mylist)

['E', 'C', 'B', 'A', 'D', 'F', 'G', 'H']


In [19]:
# To reproduce
random.seed(0)

In [20]:
# Random module is not recommended for security purposes, instead we should use secrets module
import secrets
a = secrets.randbelow(10)
print(a)

6


In [23]:
# generate random number b/w 0 and 15(1111)
a = secrets.randbits(4)
print(a)

9


In [24]:
mylist = list("ABCDEFGH")
a = secrets.choice(mylist)
print(a)

H


In [25]:
import numpy as np
np.random.seed(1)
# rand(d0,d1,…,dn)
# generate nd array with random floats, arrays has size (d0,d1,…,dn)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [26]:
# reset the seed
np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [27]:
# generate nd array with random integers in range [a,b) with size n
values = np.random.randint(0,10,(5,3))
print(values)

[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]


In [28]:
# generate nd array with Gaussian values, array has size (d0,d1,…,dn)
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
values = np.random.randn(5)
print(values)

[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]


In [29]:
# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [7 8 9]
 [1 2 3]]
